# Generated by Django 5.2.8 on 2025-11-29 12:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('city', models.CharField(blank=True, help_text='City or town', max_length=100)),
                ('state', models.CharField(blank=True, help_text='State or province', max_length=100)),
                ('postal_code', models.CharField(blank=True, help_text='ZIP/Postal code', max_length=20)),
                ('country', models.CharField(default='Nepal', help_text='Country', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, help_text='Latitude for mapping (optional)', max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, help_text='Longitude for mapping (optional)', max_digits=11, null=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(45), django.core.validators.MaxValueValidator(200)])),
                ('height', models.DecimalField(blank=True, decimal_places=2, help_text='Height in cm', max_digits=5, null=True)),
                ('medical_conditions', models.TextField(blank=True)),
                ('last_donation_date', models.DateField(blank=True, null=True)),
                ('is_eligible', models.BooleanField(default=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=15)),
                ('allow_emergency_contact', models.BooleanField(default=True, help_text='Allow contact for emergency blood requests')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group_needed', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3)),
                ('units_needed', models.PositiveIntegerField()),
                ('hospital_name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(max_length=100)),
                ('contact_phone', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=200)),
                ('urgency_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('required_by', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('fulfilled', 'Fulfilled'), ('expired', 'Expired')], default='active', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-urgency_level', '-created_at'],
                'indexes': [models.Index(fields=['status'], name='donor_emerg_status_4799ab_idx'), models.Index(fields=['blood_group_needed', 'status'], name='donor_emerg_blood_g_bdbbe5_idx'), models.Index(fields=['-urgency_level', '-created_at'], name='donor_emerg_urgency_8d9488_idx'), models.Index(fields=['required_by'], name='donor_emerg_require_b72188_idx')],
            },
        ),
        migrations.CreateModel(
            name='HealthMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('blood_pressure_systolic', models.IntegerField(blank=True, null=True)),
                ('blood_pressure_diastolic', models.IntegerField(blank=True, null=True)),
                ('resting_heart_rate', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_metrics', to='donor.donor')),
            ],
            options={
                'verbose_name': 'Health Metrics',
                'verbose_name_plural': 'Health Metrics',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(default='Nepal', max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('hospital_type', models.CharField(choices=[('government', 'Government Hospital'), ('private', 'Private Hospital'), ('blood_bank', 'Blood Bank'), ('clinic', 'Clinic'), ('medical_college', 'Medical College')], default='government', max_length=50)),
                ('has_blood_bank', models.BooleanField(default=True)),
                ('accepts_donations', models.BooleanField(default=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=15)),
                ('operating_hours', models.CharField(default='24/7', max_length=100)),
                ('services', models.TextField(default='Blood Collection, Blood Testing, Emergency Supply', help_text='Comma-separated list of services')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_user', models.OneToOneField(help_text='Admin user who manages this hospital', on_delete=django.db.models.deletion.CASCADE, related_name='hospital', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_message', models.TextField(blank=True, help_text="Donor's response message")),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('responded_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('units_donated', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('donation_notes', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_emergency_responses', to=settings.AUTH_USER_MODEL)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_responses', to='donor.donor')),
                ('emergency_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='donor.emergencyrequest')),
                ('selected_hospital', models.ForeignKey(blank=True, help_text='Hospital selected by donor if multiple options', null=True, on_delete=django.db.models.deletion.SET_NULL, to='donor.hospital')),
            ],
            options={
                'ordering': ['-responded_at'],
            },
        ),
        migrations.CreateModel(
            name='DonationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_date', models.DateField()),
                ('preferred_time', models.TimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_requests', to=settings.AUTH_USER_MODEL)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donor.donor')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donation_requests', to='donor.hospital')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DonationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_date', models.DateField()),
                ('donation_center_name', models.CharField(blank=True, max_length=200)),
                ('units_donated', models.DecimalField(decimal_places=1, default=1.0, max_digits=3)),
                ('blood_pressure', models.CharField(blank=True, max_length=20)),
                ('hemoglobin_level', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('notes', models.TextField(blank=True)),
                ('pre_donation_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('pulse_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donor.donor')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donation_histories', to='donor.hospital')),
            ],
            options={
                'verbose_name_plural': 'Donation histories',
                'ordering': ['-donation_date'],
            },
        ),
        migrations.CreateModel(
            name='BloodInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5)),
                ('units_available', models.FloatField(default=0.0)),
                ('units_reserved', models.FloatField(default=0.0, help_text='Units reserved for specific requests')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Notes about inventory changes')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_inventory', to='donor.hospital')),
            ],
            options={
                'verbose_name_plural': 'Blood Inventories',
                'ordering': ['hospital', 'blood_group'],
            },
        ),
        migrations.AddIndex(
            model_name='donor',
            index=models.Index(fields=['blood_group'], name='donor_donor_blood_g_20b659_idx'),
        ),
        migrations.AddIndex(
            model_name='donor',
            index=models.Index(fields=['is_eligible'], name='donor_donor_is_elig_5cd481_idx'),
        ),
        migrations.AddIndex(
            model_name='donor',
            index=models.Index(fields=['city', 'state'], name='donor_donor_city_5b1b57_idx'),
        ),
        migrations.AddIndex(
            model_name='donor',
            index=models.Index(fields=['latitude', 'longitude'], name='donor_donor_latitud_470122_idx'),
        ),
        migrations.AddIndex(
            model_name='donor',
            index=models.Index(fields=['-created_at'], name='donor_donor_created_dfefcf_idx'),
        ),
        migrations.AddIndex(
            model_name='donor',
            index=models.Index(fields=['allow_emergency_contact', 'blood_group'], name='donor_donor_allow_e_dc3860_idx'),
        ),
        migrations.AddIndex(
            model_name='hospital',
            index=models.Index(fields=['is_active', 'accepts_donations'], name='donor_hospi_is_acti_96505b_idx'),
        ),
        migrations.AddIndex(
            model_name='hospital',
            index=models.Index(fields=['city'], name='donor_hospi_city_08316e_idx'),
        ),
        migrations.AddIndex(
            model_name='hospital',
            index=models.Index(fields=['latitude', 'longitude'], name='donor_hospi_latitud_b436ed_idx'),
        ),
        migrations.AddIndex(
            model_name='hospital',
            index=models.Index(fields=['hospital_type'], name='donor_hospi_hospita_1cdd3d_idx'),
        ),
        migrations.AddIndex(
            model_name='emergencyresponse',
            index=models.Index(fields=['status'], name='donor_emerg_status_491eb8_idx'),
        ),
        migrations.AddIndex(
            model_name='emergencyresponse',
            index=models.Index(fields=['emergency_request', 'status'], name='donor_emerg_emergen_a7cf56_idx'),
        ),
        migrations.AddIndex(
            model_name='emergencyresponse',
            index=models.Index(fields=['-responded_at'], name='donor_emerg_respond_a75c56_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='emergencyresponse',
            unique_together={('emergency_request', 'donor')},
        ),
        migrations.AddIndex(
            model_name='donationrequest',
            index=models.Index(fields=['status'], name='donor_donat_status_f7b4e0_idx'),
        ),
        migrations.AddIndex(
            model_name='donationrequest',
            index=models.Index(fields=['status', '-created_at'], name='donor_donat_status_7682b1_idx'),
        ),
        migrations.AddIndex(
            model_name='donationrequest',
            index=models.Index(fields=['requested_date'], name='donor_donat_request_6626ce_idx'),
        ),
        migrations.AddIndex(
            model_name='donationrequest',
            index=models.Index(fields=['-created_at'], name='donor_donat_created_0b146f_idx'),
        ),
        migrations.AddIndex(
            model_name='donationhistory',
            index=models.Index(fields=['-donation_date'], name='donor_donat_donatio_e0ebe1_idx'),
        ),
        migrations.AddIndex(
            model_name='donationhistory',
            index=models.Index(fields=['donor', '-donation_date'], name='donor_donat_donor_i_1599f8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bloodinventory',
            unique_together={('hospital', 'blood_group')},
        ),
    ]
