# Generated by Django 5.2.8 on 2025-11-30 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthmetrics',
            name='hemoglobin_level',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Hemoglobin level in g/dL', max_digits=4, null=True),
        ),
    ]
