# Generated by Django 5.2.1 on 2025-07-30 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0002_donor_city_donor_country_donor_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('blood_pressure_systolic', models.IntegerField(blank=True, null=True)),
                ('blood_pressure_diastolic', models.IntegerField(blank=True, null=True)),
                ('resting_heart_rate', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_metrics', to='donor.donor')),
            ],
            options={
                'verbose_name': 'Health Metrics',
                'verbose_name_plural': 'Health Metrics',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
