# Generated by Django 5.2.8 on 2025-11-30 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0002_healthmetrics_hemoglobin_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyrequest',
            name='hospital',
            field=models.ForeignKey(blank=True, help_text='Hospital requesting emergency blood', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emergency_requests', to='donor.hospital'),
        ),
        migrations.AlterField(
            model_name='emergencyrequest',
            name='hospital_name',
            field=models.CharField(help_text='Hospital name (for backward compatibility)', max_length=200),
        ),
    ]
