# Generated by Django 5.2.1 on 2025-09-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0006_remove_donationrequest_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodinventory',
            name='units_reserved',
            field=models.FloatField(default=0.0, help_text='Units reserved for specific requests'),
        ),
    ]
