# Generated by Django 5.2.1 on 2025-09-07 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0007_add_units_reserved_to_bloodinventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationhistory',
            name='donation_center',
        ),
        migrations.AddField(
            model_name='donationhistory',
            name='blood_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='donor.donationcenter'),
        ),
        migrations.AddField(
            model_name='donationhistory',
            name='donation_center_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='donationhistory',
            name='pre_donation_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='donationhistory',
            name='pulse_rate',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donationhistory',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
    ]
