# Generated by Django 5.2.1 on 2025-09-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0008_remove_donationhistory_donation_center_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(default='Nepal', max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('hospital_type', models.CharField(choices=[('government', 'Government Hospital'), ('private', 'Private Hospital'), ('blood_bank', 'Blood Bank'), ('clinic', 'Clinic'), ('medical_college', 'Medical College')], default='government', max_length=50)),
                ('has_blood_bank', models.BooleanField(default=True)),
                ('accepts_donations', models.BooleanField(default=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=15)),
                ('operating_hours', models.CharField(default='24/7', max_length=100)),
                ('services', models.TextField(default='Blood Collection, Blood Testing, Emergency Supply', help_text='Comma-separated list of services')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
