# Generated by Django 5.1.5 on 2025-10-25 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0009_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationrequest',
            name='donation_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donation_requests', to='donor.donationcenter'),
        ),
    ]
