# Generated by Django 5.2.8 on 2025-11-15 13:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0010_add_donation_center_to_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='donationcenter',
            index=models.Index(fields=['is_active'], name='donor_donat_is_acti_0b4795_idx'),
        ),
        migrations.AddIndex(
            model_name='donationcenter',
            index=models.Index(fields=['city'], name='donor_donat_city_afb2d1_idx'),
        ),
        migrations.AddIndex(
            model_name='donationhistory',
            index=models.Index(fields=['-donation_date'], name='donor_donat_donatio_e0ebe1_idx'),
        ),
        migrations.AddIndex(
            model_name='donationhistory',
            index=models.Index(fields=['donor', '-donation_date'], name='donor_donat_donor_i_1599f8_idx'),
        ),
        migrations.AddIndex(
            model_name='donationrequest',
            index=models.Index(fields=['status'], name='donor_donat_status_f7b4e0_idx'),
        ),
        migrations.AddIndex(
            model_name='donationrequest',
            index=models.Index(fields=['status', '-created_at'], name='donor_donat_status_7682b1_idx'),
        ),
        migrations.AddIndex(
            model_name='donationrequest',
            index=models.Index(fields=['requested_date'], name='donor_donat_request_6626ce_idx'),
        ),
        migrations.AddIndex(
            model_name='donationrequest',
            index=models.Index(fields=['-created_at'], name='donor_donat_created_0b146f_idx'),
        ),
        migrations.AddIndex(
            model_name='donor',
            index=models.Index(fields=['blood_group'], name='donor_donor_blood_g_20b659_idx'),
        ),
        migrations.AddIndex(
            model_name='donor',
            index=models.Index(fields=['is_eligible'], name='donor_donor_is_elig_5cd481_idx'),
        ),
        migrations.AddIndex(
            model_name='donor',
            index=models.Index(fields=['city', 'state'], name='donor_donor_city_5b1b57_idx'),
        ),
        migrations.AddIndex(
            model_name='donor',
            index=models.Index(fields=['latitude', 'longitude'], name='donor_donor_latitud_470122_idx'),
        ),
        migrations.AddIndex(
            model_name='donor',
            index=models.Index(fields=['-created_at'], name='donor_donor_created_dfefcf_idx'),
        ),
        migrations.AddIndex(
            model_name='donor',
            index=models.Index(fields=['allow_emergency_contact', 'blood_group'], name='donor_donor_allow_e_dc3860_idx'),
        ),
        migrations.AddIndex(
            model_name='emergencyrequest',
            index=models.Index(fields=['status'], name='donor_emerg_status_4799ab_idx'),
        ),
        migrations.AddIndex(
            model_name='emergencyrequest',
            index=models.Index(fields=['blood_group_needed', 'status'], name='donor_emerg_blood_g_bdbbe5_idx'),
        ),
        migrations.AddIndex(
            model_name='emergencyrequest',
            index=models.Index(fields=['-urgency_level', '-created_at'], name='donor_emerg_urgency_8d9488_idx'),
        ),
        migrations.AddIndex(
            model_name='emergencyrequest',
            index=models.Index(fields=['required_by'], name='donor_emerg_require_b72188_idx'),
        ),
        migrations.AddIndex(
            model_name='hospital',
            index=models.Index(fields=['is_active', 'accepts_donations'], name='donor_hospi_is_acti_96505b_idx'),
        ),
        migrations.AddIndex(
            model_name='hospital',
            index=models.Index(fields=['city'], name='donor_hospi_city_08316e_idx'),
        ),
        migrations.AddIndex(
            model_name='hospital',
            index=models.Index(fields=['latitude', 'longitude'], name='donor_hospi_latitud_b436ed_idx'),
        ),
        migrations.AddIndex(
            model_name='hospital',
            index=models.Index(fields=['hospital_type'], name='donor_hospi_hospita_1cdd3d_idx'),
        ),
    ]
