# Generated by Django 5.2.8 on 2025-11-15 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0011_add_database_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_message', models.TextField(blank=True, help_text="Donor's response message")),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('responded_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('units_donated', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('donation_notes', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_emergency_responses', to=settings.AUTH_USER_MODEL)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_responses', to='donor.donor')),
                ('emergency_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='donor.emergencyrequest')),
                ('selected_hospital', models.ForeignKey(blank=True, help_text='Hospital selected by donor if multiple options', null=True, on_delete=django.db.models.deletion.SET_NULL, to='donor.hospital')),
            ],
            options={
                'ordering': ['-responded_at'],
                'indexes': [models.Index(fields=['status'], name='donor_emerg_status_491eb8_idx'), models.Index(fields=['emergency_request', 'status'], name='donor_emerg_emergen_a7cf56_idx'), models.Index(fields=['-responded_at'], name='donor_emerg_respond_a75c56_idx')],
                'unique_together': {('emergency_request', 'donor')},
            },
        ),
    ]
