# Generated by Django 5.2.8 on 2025-11-16 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0012_add_emergency_response_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_level', models.IntegerField(default=1)),
                ('total_xp', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('donor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='level_info', to='donor.donor')),
            ],
        ),
        migrations.CreateModel(
            name='DonorStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('last_donation_date', models.DateField(blank=True, null=True)),
                ('donor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak_info', to='donor.donor')),
            ],
        ),
        migrations.CreateModel(
            name='DonorAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_type', models.CharField(choices=[('first_drop', 'First Drop - First donation'), ('regular', 'Regular Donor - 5 donations'), ('hero', 'Hero Donor - 10 donations'), ('platinum', 'Platinum Donor - 25 donations'), ('legend', 'Legend - 50+ donations'), ('quick_responder', 'Quick Responder - Emergency response'), ('streak_3', 'Streak Master - 3 consecutive donations'), ('perfect_record', 'Perfect Record - Never missed appointment'), ('bullseye', 'Bullseye - Donated on exact eligible date'), ('community_hero', 'Community Hero - Helped 5+ hospitals')], max_length=30)),
                ('earned_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='donor.donor')),
            ],
            options={
                'ordering': ['-earned_date'],
                'unique_together': {('donor', 'achievement_type')},
            },
        ),
    ]
