# Generated by Django 5.1.5 on 2025-10-25 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donor', '0009_hospital'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(blank=True, help_text='City or town', max_length=100)),
                ('state', models.CharField(blank=True, help_text='State or province', max_length=100)),
                ('postal_code', models.CharField(blank=True, help_text='ZIP/Postal code', max_length=20)),
                ('country', models.CharField(default='Nepal', help_text='Country', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, help_text='Latitude for mapping (optional)', max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, help_text='Longitude for mapping (optional)', max_digits=11, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='admin_photos/')),
                ('department', models.CharField(default='Blood Bank Management', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SystemNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('urgent', 'Urgent'), ('maintenance', 'Maintenance'), ('donation_scheduled', 'Donation Scheduled'), ('donation_reminder', 'Donation Reminder'), ('emergency_request', 'Emergency Blood Request'), ('donation_completed', 'Donation Completed'), ('eligibility_update', 'Eligibility Update')], default='info', max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('target_audience', models.CharField(choices=[('all', 'All Users'), ('donors', 'Donors Only'), ('admins', 'Admins Only')], default='all', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('action_url', models.URLField(blank=True, help_text='Optional URL for action button')),
                ('is_read', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('donation_scheduled', 'Donation Scheduled'), ('donation_reminder', 'Donation Reminder'), ('donation_completed', 'Donation Completed'), ('emergency_request', 'Emergency Blood Request'), ('eligibility_restored', 'Eligibility Restored'), ('profile_updated', 'Profile Updated'), ('location_updated', 'Location Updated'), ('health_metrics_added', 'Health Metrics Added'), ('request_approved', 'Request Approved'), ('request_rejected', 'Request Rejected')], max_length=30)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action_url', models.URLField(blank=True)),
                ('related_donation_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='donor.donationrequest')),
                ('related_emergency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='donor.emergencyrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemNotificationRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('system_notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.systemnotification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-read_at'],
                'unique_together': {('user', 'system_notification')},
            },
        ),
    ]
