# Generated by Django 5.2.1 on 2025-07-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='city',
            field=models.CharField(blank=True, help_text='City or town', max_length=100),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='country',
            field=models.CharField(default='Nepal', help_text='Country', max_length=100),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Latitude for mapping (optional)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Longitude for mapping (optional)', max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='postal_code',
            field=models.CharField(blank=True, help_text='ZIP/Postal code', max_length=20),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='state',
            field=models.CharField(blank=True, help_text='State or province', max_length=100),
        ),
    ]
