# Generated by Django 5.2.1 on 2025-07-31 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_adminprofile_city_adminprofile_country_and_more'),
        ('donor', '0003_healthmetrics'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='systemnotification',
            name='action_url',
            field=models.URLField(blank=True, help_text='Optional URL for action button'),
        ),
        migrations.AddField(
            model_name='systemnotification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemnotification',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='systemnotification',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='systemnotification',
            name='notification_type',
            field=models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('urgent', 'Urgent'), ('maintenance', 'Maintenance'), ('donation_scheduled', 'Donation Scheduled'), ('donation_reminder', 'Donation Reminder'), ('emergency_request', 'Emergency Blood Request'), ('donation_completed', 'Donation Completed'), ('eligibility_update', 'Eligibility Update')], default='info', max_length=30),
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('donation_scheduled', 'Donation Scheduled'), ('donation_reminder', 'Donation Reminder'), ('donation_completed', 'Donation Completed'), ('emergency_request', 'Emergency Blood Request'), ('eligibility_restored', 'Eligibility Restored'), ('profile_updated', 'Profile Updated'), ('location_updated', 'Location Updated'), ('health_metrics_added', 'Health Metrics Added'), ('request_approved', 'Request Approved'), ('request_rejected', 'Request Rejected')], max_length=30)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action_url', models.URLField(blank=True)),
                ('related_donation_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='donor.donationrequest')),
                ('related_emergency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='donor.emergencyrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
